version: "3.2"
services:
  api:
    image: flask_api
    container_name: ml_api
    build:
      context: ./API

      target: build
    
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model
    volumes:
      - ./feedback:/src/feedback
   
  db:
      image: mysql:5.7
      container_name: db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'martin'
        MYSQL_DATABASE: "mysql"
        MYSQL_USER: "db_user"
        MYSQL_PASSWORD: 'martinlinux'
      ports:
        - "32000:3306"
      volumes:
        - ./schemas:/src/mysql:rw
      

        
  redis:
    image: redis:6.2.6

  model:
    image: model
    build:
      context: ./models
      target: build
    depends_on:
      - redis


volumes:
  schemas : {}